GCC=gcc
FLAGS=-Wall

SLAVE=slave.o
SLAVE_SOURCES=slave.c

APPLICATION=application.out
APPLICATION_SOURCES=application.c

FILEPARSER=fileListParser.o
FILEPARSER_SOURCES=fileListParser.c

all: $(SLAVE) $(APPLICATION)

$(SLAVE): $(SLAVE_SOURCES)
	$(GCC) $(FLAGS) $(SLAVE_SOURCES) -o $(SLAVE)

$(APPLICATION): $(APPLICATION_SOURCES) $(FILEPARSER)
	$(GCC) $(FLAGS) $(APPLICATION_SOURCES) $(FILEPARSER) -o $(APPLICATION)

$(FILEPARSER): $(FILEPARSER_SOURCES)
	$(GCC) $(FLAGS) -c $(FILEPARSER_SOURCES)

clean:
	rm -rf *.o $(APPLICATION)

.PHONY: all clean
