GCC=gcc
FLAGS=-Wall

SLAVE=slave.o
SLAVE_SOURCES=slave.c

APPLICATION=application.out
APPLICATION_SOURCES=application.c

APPLICATION_LIB=applicationLib.o
APPLICATION_LIB_SOURCES=applicationLib.c

VIEW=view.out
VIEW_SOURCES=view.c

FILE_PARSER=fileListParser.o
FILE_PARSER_SOURCES=fileListParser.c

SHARED_MEMORY=sharedMemory.o
SHARED_MEMORY_SOURCES=sharedMemory.c

all: $(SLAVE) $(APPLICATION) $(VIEW)

$(SLAVE): $(SLAVE_SOURCES)
	$(GCC) $(FLAGS) $(SLAVE_SOURCES) -o $(SLAVE)

$(APPLICATION): $(APPLICATION_SOURCES) $(FILE_PARSER) $(SHARED_MEMORY) $(APPLICATION_LIB)
	$(GCC) $(FLAGS) $(APPLICATION_SOURCES) $(APPLICATION_LIB) $(FILE_PARSER) $(SHARED_MEMORY) -o $(APPLICATION)

$(VIEW): $(SLAVE_SOURCES) $(SHARED_MEMORY)
	$(GCC) $(FLAGS) $(VIEW_SOURCES) $(SHARED_MEMORY) -o $(VIEW)

$(FILE_PARSER): $(FILE_PARSER_SOURCES)
	$(GCC) $(FLAGS) -c $(FILE_PARSER_SOURCES)

$(SHARED_MEMORY): $(SHARED_MEMORY_SOURCES)
	$(GCC) $(FLAGS) -c $(SHARED_MEMORY_SOURCES)

$(APPLICATION_LIB): $(APPLICATION_LIB_SOURCES)
	$(GCC) $(FLAGS) -c $(APPLICATION_LIB_SOURCES)

clean:
	rm -rf *.o *.out

.PHONY: all clean
